name: Run Unit Tests

on:
  push

jobs:

  run_tests:

    runs-on: ubuntu-latest

    steps:

      - name: Get sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installing dependencies
        run: pip install --upgrade pip black --quiet

      # - name: Style check
      #   run: black . --check

      - name: Install module
        run: pip install -e .

      - name: Running tests
        run: python -m unittest discover -s tests -p *_test.py
